version: "3.9"
services:
  admin-frontend:
    container_name: portfolio
    build:
      context: ./
      target: runner
      args:
        - aaaaaa
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file:
      - .env.local
