version: "3.9"
services:
  admin-frontend:
    container_name: portfolio
    build:
      context: ./
      target: runner
      args:
        - NEXT_PUBLIC_BACKEND=https://portfolio-backend-ruaudzasaq-an.a.run.app
    ports:
      - 3000:3000
    env_file:
      - .env.local
