name: Build and Publish DockerImage

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          tags: latest
          image: hackmeet-frontent
          registry: 933345684592.dkr.ecr.ap-northeast-1.amazonaws.com
          buildArgs: NEXT_PUBLIC_BACKEND, NEXT_PUBLIC_REGION, NEXT_PUBLIC_BUCKET_NAME, NEXT_PUBLIC_ACCESS_KEY, NEXT_PUBLIC_SECRET_KEY, NEXT_PUBLIC_SECRET_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_BACKEND: ${{ secrets.NEXT_PUBLIC_BACKEND }}
          NEXT_PUBLIC_REGION: ${{ secrets.NEXT_PUBLIC_REGION }}
          NEXT_PUBLIC_BUCKET_NAME: ${{ secrets.NEXT_PUBLIC_BUCKET_NAME }}
          NEXT_PUBLIC_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_ACCESS_KEY }}
          NEXT_PUBLIC_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_SECRET_KEY }}
          NEXT_PUBLIC_S3_URL: ${{ secrets.NEXT_PUBLIC_S3_URL }}
